### ISSUE TITLE
Change login page copy post migration

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/delphin#1171]
During migration to WordPress.com, maintenance mode will be enabled, changing the copy on the login page. After migration we need to adjust that copy again we a permanent message about accounts moving to WordPress.com

Using the same layout as the maintenance mode (#1169) here's the copy:

Copy:

> **Get.blog has moved to WordPress.com**
>
> We have merged the ease of use of get.blog with the power of WordPress.com. Get.blog domains are now managed at WordPress.com.
>
> If you purchased a domain on get.blog, we sent you an email with instructions to log in and manage your domains on WordPress.com. Check your email for more information or visit WordPress.com now to [create your password](#).
>
> For any questions, please contact us at [help@wordpress.com](#).

cc @ranh @wensco @klimeryk @delputnam

**Comment by ranh** [comment]
Maybe instead of "we have merged [...]", how about:

> Your get.blog domains can now be managed on WordPress.com. Enjoy the ease of use of get.blog, now with the power of WordPress.com.

**Comment by mikeshelton1503** [comment]
Good points, thanks @ranh! Let's go with those edits :)

**Comment by ranh** [comment]
> Your get.blog domains can be managed on WordPress.com.

@klimeryk mentioned that it's not clear enough that WordPress.com is the _only_ option now. Let's keep Mike's original:

> Get.blog domains are now managed at WordPress.com. Enjoy the ease of use of get.blog with the power of WordPress.com.

**Comment by klimeryk** [comment]
Resolved by https://github.com/Automattic/delphin/pull/1172
