### ISSUE TITLE
Domain Setup: Add "Exit" link

### ISSUE THREAD

**Issue by mikeshelton1503** [Automattic/delphin#885]
In #764 we updated the look of the domain setup header, however the "Exit" link didn't get implemented yet.

![image](https://cloud.githubusercontent.com/assets/12596797/20191265/bbabf520-a752-11e6-9899-9027916ed310.png)

Clicking "Exit" should take you back to My Domains, ideally saving your progress.

**Comment by aidvu** [comment]
Fixed.
